# Generated by Django 6.0.1 on 2026-01-31 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User's Name (e.g., Zhang San)", max_length=100)),
                ('platform_username', models.CharField(help_text='Login Username', max_length=100)),
                ('platform_password', models.CharField(help_text='Login Password', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, help_text='The secret key string', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_time', models.DateTimeField(blank=True, help_text='Optional expiry time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_auth.volunteeraccount')),
            ],
        ),
    ]
