# Generated by Django 6.0.1 on 2026-02-01 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscard',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='If True, card never expires'),
        ),
        migrations.AddField(
            model_name='accesscard',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Login user for this card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to=settings.AUTH_USER_MODEL),
        ),
    ]
