# Generated by Django 6.0.1 on 2026-02-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_auth', '0002_accesscard_auto_renew_accesscard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscard',
            name='bound_device_id',
            field=models.CharField(blank=True, help_text='Unique ID of the first browser used', max_length=100, null=True),
        ),
    ]
